uArch dependency support
riscv-software-src/riscv-config pull request #126
Opened 2023-04-25 11:46 UTC by iamkarthikbk

WARL CSRs can now include hidden uArch dependencies in their YAML definitions.

the `warl_class` now creates a `uarch_depends` dict to support adding hidden uArch
signals to the dependency string in a CSR's YAML definition.

1. The prefix for such a signal/group must be `uarch_`. For example -
  - `uarch_cachecontrol` is a valid group/signal. In order to group signals under this
    name, `uarch_cachecontrol::global_valid` and `uarch_cachecontrol::global_dirty` are
    valid dependencies.
  - `uarch_global_valid` and `uarch_global_dirty` are valid signals. Such signals, for
    parsing purposes are grouped with an implicit name `uarch_commonconfig`. This name
    can not be used for any other micro-architectural signal dependency.

2. Any such signals/groups will be excluded from error checks, and will evaluate to
   `True` for legal checks.

3. Upon encountering such a signal/group, a warning statement will be logged:

```text
[DEBUG]   riscv_config.checker: -- Checking reset values for csr: mtvec::base
[WARNING] riscv_config.warl: WARL for csr mtvec::base depends on uarch csr uarch_global_valid. Treating this as a uarch dependency and excluding from all furtherchecks.
[DEBUG]   riscv_config.warl: uArch dependencies are: {'uarch_commonconfig':['uarch_global_valid']}
[WARNING] riscv_config.warl: WARL for csr mtvec::base depends on uarch csr uarch_global_dirty. Treating this as a uarch dependency and excluding from all further checks.
[DEBUG]   riscv_config.warl: uArch dependencies are: {'uarch_commonconfig': ['uarch_global_valid', 'uarch_global_dirty']}
[DEBUG]   riscv_config.warl: ---- WARL Value Legality Check: value:0 csr:mtvec::base dependency_vals:None
[WARNING] riscv_config.warl: csr/subfield uarch_global_valid is a uArch dependency.
[WARNING] riscv_config.warl: csr/subfield uarch_global_dirty is a uArch dependency.
[DEBUG]   riscv_config.warl:  warl legal string "uarch_global_valid[3:0] in [0] and uarch_global_dirty[3:0] in [0] -> base[61:0] bitmask [0x3FFFFFFFFFFFFFFF, 0x0000000000000000]" treats the input value 0 as legal
```

4. Such signals will show up in the checked YAMLs as follows:

if grouped --
```text
warl:
  dependency_fields: [uarch_cachecontrol::global_valid, uarch_cachecontrol::global_dirty]
  legal:
    - global_valid[3:0] in [0] and global_dirty[3:0] in [0]
      -> base[61:0] bitmask [0x3FFFFFFFFFFFFFFF, 0x0000000000000000]
  wr_illegal:
    - Unchanged
```

or if not grouped --
```text
warl:
    dependency_fields: [uarch_global_valid, uarch_global_dirty]
    legal:
        - uarch_global_valid[3:0] in [0] and uarch_global_dirty[3:0]
        in [0] -> base[61:0] bitmask [0x3FFFFFFFFFFFFFFF, 0x0000000000000000]
    wr_illegal:
        - Unchanged
```

2023-04-25 12:05 UTC, pawks commented
Please update the docs for warl([link](https://github.com/riscv-software-src/riscv-config/blob/master/docs/source/yaml-specs.rst#warl-node-definition)) with the corresponding information.

2023-04-26 20:03 UTC, iamKarthikBK commented
ready for review @pawks

2023-05-05 06:18 UTC, pawks requested changes

2023-05-05 06:18 UTC, pawks commented on riscv_config/warl.py
> +        self.uarch_signals = uarch_signals
Can be derived from the `spec` variable itself. Prevents making a non-backward compatible API change.

2023-05-05 06:18 UTC, pawks commented on riscv_config/schemas/schema_custom.yaml
> +                max: 0xFFFFFFFFFFFFFFFF
No Max value required.

2023-05-05 06:18 UTC, pawks commented on riscv_config/schemas/schema_custom.yaml
> +                    max: 62
No max value required.

2023-05-05 06:18 UTC, pawks commented on riscv_config/schemas/schema_custom.yaml
> +                    max: 63
No Max value required.

2023-05-05 06:18 UTC, pawks commented on riscv_config/schemas/schema_custom.yaml
> +                    min: 1
min of lsb cant be greater than msb. Additionally, the way schema is defined, each subfield will have to be a minimum of 2 bits wide. No min-max bounds are necessary for these registers. The schema would also benefit from an additional check_with function to ensure that the subfields are non-overlapping.

2023-05-15 11:24 UTC, pawks approved these changes
LGTM!

2023-05-16 12:58 UTC, merged